import { IncidentsData } from "./types";

export const incidentsData: IncidentsData = {
  incidents: [
    {
      id: 1,
      title: "다이아틀로프 고개 사건",
      category: "mystery",
      era: "modern",
      date: "1959-02-02",
      location: "러시아 우랄산맥",
      summary: "9명의 등산객이 텐트를 찢고 도주한 후 의문의 죽음을 맞은 사건",
      description:
        "1959년 2월, 우랄 공과대학의 등산팀 9명이 우랄산맥 북부의 다이아틀로프 고개에서 의문사했다. 수색대는 텐트가 내부에서 찢겨진 채 발견했으며, 일부 시신은 영하 30도의 날씨에 속옷 차림이었고, 일부는 심각한 외상을 입었다. 방사능 오염, 이상한 피부 변색 등 설명되지 않는 증거들이 발견되었다.",
      timeline: [
        { date: "1959-01-25", event: "등산팀 출발" },
        { date: "1959-02-01", event: "마지막 캠프 설치" },
        { date: "1959-02-02", event: "추정 사망 시점" },
        { date: "1959-02-26", event: "수색대에 의해 첫 시신 발견" },
      ],
      theories: ["눈사태", "군사 실험", "선주민 공격", "인프라사운드", "눈보라 공황"],
      tags: ["미스터리", "집단 사망", "러시아", "등산", "미제"],
      sources: [
        { name: "위키피디아", url: "https://ko.wikipedia.org/wiki/댜틀로프_사건" },
      ],
      relatedIncidents: [2, 5],
    },
    {
      id: 2,
      title: "버뮤다 삼각지대 실종 사건",
      category: "mystery",
      era: "contemporary",
      date: "1945-12-05",
      location: "대서양 버뮤다 해역",
      summary: "수많은 선박과 항공기가 의문의 실종을 당한 해역",
      description:
        "버뮤다, 플로리다, 푸에르토리코를 연결하는 삼각 해역에서 19세기부터 현재까지 수많은 선박과 항공기가 흔적 없이 사라졌다. 가장 유명한 사건은 1945년 미 해군 비행편대 19(Flight 19)의 실종으로, 5대의 어뢰 폭격기가 훈련 중 사라졌다.",
      timeline: [
        { date: "1945-12-05", event: "Flight 19 실종" },
        { date: "1948-01-30", event: "Star Tiger 여객기 실종" },
        { date: "1963-02-02", event: "SS Marine Sulphur Queen 화물선 실종" },
      ],
      theories: ["메탄 가스 분출", "자기장 이상", "인간 실수", "해류", "외계인"],
      tags: ["미스터리", "실종", "대서양", "비행기", "선박"],
      sources: [
        {
          name: "History Channel",
          url: "https://www.history.com/topics/paranormal/bermuda-triangle",
        },
      ],
      relatedIncidents: [1, 7],
    },
    {
      id: 3,
      title: "잭 더 리퍼 연쇄살인",
      category: "crime",
      era: "modern",
      date: "1888-08-31",
      location: "영국 런던 화이트채플",
      summary: "1888년 런던에서 발생한 미해결 연쇄살인 사건",
      description:
        "1888년 8월부터 11월까지 런던 화이트채플 지역에서 최소 5명의 여성이 잔인하게 살해되었다. 범인은 외과적 정밀도로 피해자들을 해부했으며, 경찰과 언론에 조롱 편지를 보냈다. 범인의 정체는 130년이 지난 지금도 밝혀지지 않았다.",
      timeline: [
        { date: "1888-08-31", event: "메리 앤 니콜스 살해" },
        { date: "1888-09-08", event: "애니 채프먼 살해" },
        { date: "1888-09-30", event: "엘리자베스 스트라이드, 캐서린 에도우스 살해" },
        { date: "1888-11-09", event: "메리 제인 켈리 살해" },
      ],
      theories: ["왕실 음모", "의사 범행", "정신병자", "다중 범인"],
      tags: ["연쇄살인", "미제", "영국", "빅토리아 시대"],
      sources: [{ name: "Casebook.org", url: "https://www.casebook.org/" }],
      relatedIncidents: [4, 9],
    },
    {
      id: 4,
      title: "조디악 킬러",
      category: "unsolved",
      era: "contemporary",
      date: "1968-12-20",
      location: "미국 캘리포니아",
      summary: "암호 편지를 보낸 미해결 연쇄살인범",
      description:
        "1968년부터 1969년 사이 캘리포니아 북부에서 최소 5명을 살해한 연쇄살인범. 범인은 언론사에 암호화된 편지를 보내 자신의 정체를 추측하게 했다. 4개의 암호 중 2개만 해독되었으며, 범인은 끝내 잡히지 않았다.",
      timeline: [
        { date: "1968-12-20", event: "첫 번째 공격 (베티 루 젠슨, 데이비드 파라데이)" },
        { date: "1969-07-04", event: "두 번째 공격" },
        { date: "1969-08-01", event: "첫 번째 암호 편지 도착" },
        { date: "1969-09-27", event: "레이크 버리에사 공격" },
      ],
      theories: ["아서 리 앨런", "로스 설리번", "리차드 개이코스키"],
      tags: ["연쇄살인", "미제", "암호", "미국", "FBI"],
      sources: [
        { name: "FBI Records", url: "https://vault.fbi.gov/The%20Zodiac%20Killer" },
      ],
      relatedIncidents: [3, 9],
    },
    {
      id: 5,
      title: "MH370 실종 사건",
      category: "accident",
      era: "contemporary",
      date: "2014-03-08",
      location: "인도양",
      summary: "239명이 탑승한 말레이시아 항공기의 의문의 실종",
      description:
        "2014년 3월 8일, 쿠알라룸푸르에서 베이징으로 향하던 말레이시아 항공 370편이 이륙 40분 후 레이더에서 사라졌다. 항공기는 원래 경로를 이탈해 서쪽으로 방향을 틀었으며, 최종적으로 인도양 남부에 추락한 것으로 추정된다. 현재까지 일부 잔해만 발견되었다.",
      timeline: [
        { date: "2014-03-08", event: "00:41 이륙" },
        { date: "2014-03-08", event: "01:19 마지막 교신" },
        { date: "2014-03-08", event: "01:21 트랜스폰더 차단" },
        { date: "2015-07-29", event: "레위니옹 섬에서 첫 잔해 발견" },
      ],
      theories: ["조종사 자살", "기계 결함", "하이재킹", "화재"],
      tags: ["항공사고", "실종", "미제", "말레이시아"],
      sources: [
        {
          name: "Aviation Safety Network",
          url: "https://aviation-safety.net/database/record.php?id=20140308-0",
        },
      ],
      relatedIncidents: [2, 6],
    },
    {
      id: 6,
      title: "세월호 침몰 사고",
      category: "accident",
      era: "contemporary",
      date: "2014-04-16",
      location: "대한민국 진도",
      summary: "304명이 희생된 대한민국 최악의 해상 참사",
      description:
        "2014년 4월 16일, 인천에서 제주로 향하던 여객선 세월호가 진도 인근 해상에서 침몰했다. 승객 대부분이 수학여행 중이던 단원고 학생들이었으며, 부적절한 구조 대응으로 304명이 희생되었다. 이 사고는 대한민국 사회에 큰 충격을 주었다.",
      timeline: [
        { date: "2014-04-15", event: "21:00 인천항 출발" },
        { date: "2014-04-16", event: "08:48 급격한 선회 시작" },
        { date: "2014-04-16", event: "08:52 최초 조난 신호" },
        { date: "2014-04-16", event: "10:31 완전 침몰" },
      ],
      theories: ["과적", "조타 실수", "평형수 부족", "불법 개조"],
      tags: ["해상사고", "한국", "참사", "구조 실패"],
      sources: [
        { name: "세월호 참사 특별조사위원회", url: "http://www.sewolcommission.kr/" },
      ],
      relatedIncidents: [5],
    },
    {
      id: 7,
      title: "로즈웰 UFO 사건",
      category: "conspiracy",
      era: "contemporary",
      date: "1947-07-08",
      location: "미국 뉴멕시코 로즈웰",
      summary: "외계인 우주선 추락 의혹 사건",
      description:
        "1947년 7월, 뉴멕시코주 로즈웰 인근에서 정체불명의 비행체 잔해가 발견되었다. 미 육군은 처음에 '비행접시'를 회수했다고 발표했다가 곧 기상관측 기구로 정정했다. 이후 외계인 시체 회수, 역설계 등의 음모론이 퍼졌다.",
      timeline: [
        { date: "1947-07-02", event: "잔해 발견" },
        { date: "1947-07-08", event: "육군 '비행접시' 발표" },
        { date: "1947-07-09", event: "기상 기구로 정정" },
        { date: "1994", event: "미 공군 Project Mogul 해명" },
      ],
      theories: ["외계인 우주선", "기상 기구", "비밀 군사 실험", "소련 스파이 장비"],
      tags: ["UFO", "외계인", "음모론", "미국", "냉전"],
      sources: [
        { name: "FBI Records", url: "https://vault.fbi.gov/Roswell%20UFO" },
      ],
      relatedIncidents: [2, 8],
    },
    {
      id: 8,
      title: "51구역",
      category: "conspiracy",
      era: "contemporary",
      date: "1955-01-01",
      location: "미국 네바다",
      summary: "외계인 기술 역설계 의혹의 비밀 기지",
      description:
        "네바다주 사막에 위치한 미 공군의 극비 시설. 공식적으로는 실험용 항공기 개발 기지이나, UFO 잔해 보관 및 외계 기술 역설계 장소라는 음모론이 있다. 2013년 CIA가 처음으로 공식 존재를 인정했다.",
      timeline: [
        { date: "1955", event: "U-2 정찰기 개발을 위해 기지 설립" },
        { date: "1989", event: "밥 라자르 외계 기술 역설계 주장" },
        { date: "2013", event: "CIA 공식 존재 인정" },
        { date: "2019", event: "'51구역 습격' 밈 이벤트" },
      ],
      theories: ["외계인 기술 연구", "비밀 항공기 개발", "시간 여행 실험"],
      tags: ["음모론", "UFO", "미국", "군사기지", "비밀"],
      sources: [{ name: "CIA FOIA", url: "https://www.cia.gov/readingroom/" }],
      relatedIncidents: [7],
    },
    {
      id: 9,
      title: "화성 연쇄살인 사건",
      category: "crime",
      era: "contemporary",
      date: "2003-09-19",
      location: "대한민국 화성",
      summary: "10명의 여성이 희생된 대한민국 최초의 연쇄살인 사건",
      description:
        "1986년부터 1991년까지 경기도 화성에서 10명의 여성이 연쇄적으로 살해되었다. 33년간 미제로 남아있다가 2019년 DNA 검사를 통해 이춘재가 범인으로 밝혀졌다. 이 사건은 영화 '살인의 추억'의 모티브가 되었다.",
      timeline: [
        { date: "1986-09-15", event: "제1차 사건" },
        { date: "1988-09-16", event: "제7차 사건 (유일하게 DNA 확보)" },
        { date: "1991-04-03", event: "제10차 사건 (마지막)" },
        { date: "2019-09-18", event: "이춘재 범인 확인" },
      ],
      theories: ["단독범", "모방범", "공범 존재"],
      tags: ["연쇄살인", "한국", "DNA", "미제 해결"],
      sources: [{ name: "경찰청 발표", url: "https://www.police.go.kr/" }],
      relatedIncidents: [3, 4],
    },
    {
      id: 10,
      title: "이집트 피라미드 건설의 미스터리",
      category: "mystery",
      era: "ancient",
      date: "-2560-01-01",
      location: "이집트 기자",
      summary: "고대 이집트인들이 어떻게 거대한 피라미드를 건설했는지에 대한 미스터리",
      description:
        "기자의 대피라미드는 230만 개 이상의 석회암 블록으로 건설되었으며, 각 블록의 무게는 평균 2.5톤이다. 고대 이집트인들이 현대 기술 없이 어떻게 이런 정밀한 건축물을 완성했는지는 여전히 논쟁 중이다.",
      timeline: [
        { date: "-2560", event: "쿠푸 대피라미드 건설 시작 추정" },
        { date: "-2540", event: "건설 완료 추정" },
      ],
      theories: ["경사로 이론", "내부 경사로", "레버 시스템", "외계인 개입"],
      tags: ["고대 미스터리", "이집트", "건축", "피라미드"],
      sources: [{ name: "National Geographic", url: "https://www.nationalgeographic.com/" }],
      relatedIncidents: [11],
    },
    {
      id: 11,
      title: "나스카 라인",
      category: "mystery",
      era: "ancient",
      date: "0500-01-01",
      location: "페루 나스카",
      summary: "페루 사막에 새겨진 거대한 지상화의 미스터리",
      description:
        "페루 남부 나스카 사막에 있는 수백 개의 거대한 지상화. 동물, 식물, 기하학적 도형 등이 새겨져 있으며, 하늘에서만 전체 모습을 볼 수 있다. 누가, 왜 이것을 만들었는지는 여전히 미스터리다.",
      timeline: [
        { date: "500-800", event: "나스카 문명에 의해 제작 추정" },
        { date: "1927", event: "페루 고고학자에 의해 처음 발견" },
        { date: "1994", event: "유네스코 세계문화유산 등재" },
      ],
      theories: ["종교 의식", "천문 달력", "외계인 활주로", "물 숭배 의식"],
      tags: ["고대 미스터리", "페루", "지상화", "고고학"],
      sources: [{ name: "UNESCO", url: "https://whc.unesco.org/en/list/700" }],
      relatedIncidents: [10],
    },
    {
      id: 12,
      title: "체르노빌 원전 사고",
      category: "accident",
      era: "contemporary",
      date: "1986-04-26",
      location: "우크라이나 체르노빌",
      summary: "인류 역사상 최악의 원자력 발전소 사고",
      description:
        "1986년 4월 26일 새벽, 체르노빌 원자력 발전소 4호기가 폭발했다. 안전 테스트 중 연쇄 반응이 통제 불능 상태가 되어 원자로가 폭발했다. 직접 사망자 31명 외에 방사능으로 인한 장기적 피해자 수는 수만 명에 달한다.",
      timeline: [
        { date: "1986-04-26", event: "01:23 폭발 발생" },
        { date: "1986-04-27", event: "프리피야트 시 대피" },
        { date: "1986-05-14", event: "고르바초프 첫 공식 성명" },
        { date: "1986-11", event: "석관 건설 완료" },
      ],
      theories: ["운영 실수", "설계 결함", "안전 문화 부재", "소련 체제 문제"],
      tags: ["원전사고", "방사능", "소련", "재난", "우크라이나"],
      sources: [{ name: "IAEA Report", url: "https://www.iaea.org/" }],
      relatedIncidents: [13],
    },
    {
      id: 13,
      title: "후쿠시마 원전 사고",
      category: "accident",
      era: "contemporary",
      date: "2011-03-11",
      location: "일본 후쿠시마",
      summary: "동일본 대지진으로 발생한 원자력 발전소 사고",
      description:
        "2011년 3월 11일, 규모 9.0 지진과 이어진 쓰나미가 후쿠시마 제1원자력 발전소를 강타했다. 냉각 시스템 파괴로 3기의 원자로가 멜트다운되었고, 대량의 방사성 물질이 환경에 방출되었다.",
      timeline: [
        { date: "2011-03-11", event: "14:46 지진 발생" },
        { date: "2011-03-11", event: "15:41 쓰나미 도달" },
        { date: "2011-03-12", event: "1호기 수소 폭발" },
        { date: "2011-03-15", event: "4호기 화재" },
      ],
      theories: ["쓰나미 대비 부족", "냉각 시스템 결함", "규제 실패"],
      tags: ["원전사고", "쓰나미", "일본", "재난", "방사능"],
      sources: [{ name: "TEPCO Report", url: "https://www.tepco.co.jp/" }],
      relatedIncidents: [12],
    },
    {
      id: 14,
      title: "JFK 암살",
      category: "conspiracy",
      era: "contemporary",
      date: "1963-11-22",
      location: "미국 텍사스 댈러스",
      summary: "미국 대통령 암살과 그에 따른 수많은 음모론",
      description:
        "1963년 11월 22일, 존 F. 케네디 대통령이 댈러스 퍼레이드 중 총격을 받아 사망했다. 공식적으로 리 하비 오스왈드가 단독 범행한 것으로 결론났으나, 제2의 총격수, CIA 개입 등 수많은 음모론이 존재한다.",
      timeline: [
        { date: "1963-11-22", event: "12:30 총격 발생" },
        { date: "1963-11-22", event: "13:00 케네디 사망 선언" },
        { date: "1963-11-24", event: "오스왈드 피살" },
        { date: "1964-09-24", event: "워런 위원회 보고서 발표" },
      ],
      theories: ["단독범", "CIA 음모", "마피아 개입", "쿠바 관련", "제2 총격수"],
      tags: ["암살", "음모론", "미국", "대통령", "냉전"],
      sources: [
        {
          name: "Warren Commission",
          url: "https://www.archives.gov/research/jfk/warren-commission-report",
        },
      ],
      relatedIncidents: [7, 8],
    },
    {
      id: 15,
      title: "타이타닉 침몰",
      category: "accident",
      era: "modern",
      date: "1912-04-15",
      location: "북대서양",
      summary: "불침선이라 불린 호화 여객선의 처녀 항해 중 침몰",
      description:
        "1912년 4월 15일, '불침선'이라 불린 RMS 타이타닉호가 처녀 항해 중 빙산과 충돌해 침몰했다. 2,224명의 승객 중 1,500명 이상이 사망한 역사상 가장 유명한 해상 참사 중 하나다.",
      timeline: [
        { date: "1912-04-10", event: "사우샘프턴 출항" },
        { date: "1912-04-14", event: "23:40 빙산 충돌" },
        { date: "1912-04-15", event: "02:20 침몰" },
        { date: "1985-09-01", event: "잔해 발견" },
      ],
      theories: ["화재 손상", "저급 리벳", "빙산 경고 무시", "설계 결함"],
      tags: ["해상사고", "영국", "빙산", "여객선"],
      sources: [
        { name: "Encyclopedia Titanica", url: "https://www.encyclopedia-titanica.org/" },
      ],
      relatedIncidents: [6],
    },
  ],
  relations: [
    { from: 1, to: 2, relation: "유사 미스터리" },
    { from: 1, to: 5, relation: "원인 불명" },
    { from: 2, to: 7, relation: "UFO 연관" },
    { from: 3, to: 4, relation: "미제 연쇄살인" },
    { from: 3, to: 9, relation: "연쇄살인 유형" },
    { from: 4, to: 9, relation: "연쇄살인 유형" },
    { from: 5, to: 2, relation: "실종 미스터리" },
    { from: 5, to: 6, relation: "동시대 참사" },
    { from: 7, to: 8, relation: "UFO 음모론" },
    { from: 7, to: 14, relation: "정부 은폐 의혹" },
    { from: 8, to: 14, relation: "정부 은폐 의혹" },
    { from: 10, to: 11, relation: "고대 미스터리" },
    { from: 12, to: 13, relation: "원전 사고" },
    { from: 6, to: 15, relation: "해상 참사" },
  ],
};
